### ISSUE TITLE
Add Sample folder as a Samples folder displayed within Unity

### ISSUE THREAD

**Issue by Kaiymu** [crazyjackel/redmoon-reactiveKit#1]
Hello,

Currently when we pull your project, we are unable to open the BasicUI/ contained inside the Samples/ folder.
This is because you cannot access since within the package system.

Unity provide a way inside the manifest.json to do so,
I have an exemple on my project if [that helps ](https://github.com/Kaiymu/UnityHelpers/blob/main/package.json)
Also, if you put the ~ in front of your folder name, the folder won't be displayed within the package, but only could be downloaded on the PackageManager UI.

For exemple 
![image](https://user-images.githubusercontent.com/4659725/151680585-52cd2410-9a23-4c77-9beb-a3b85b212174.png)

`"samples": [
		{
			"displayName": "MySample",
			"description": "Description",
			"path": "Samples~/MySampleFolder"
		}
	]	`

Hopefully that helps !

Thank you again and have a great day.

**Comment by crazyjackel** [comment]
Yea, I am aware, was going to fix that sometime tomorrow.

This is very in-development. It is part of another bigger project that is also very in-development. (I wanted to create a development set for making games that are very moddable.)

The Sample isn't done yet.

**Comment by crazyjackel** [comment]
It is public, because it is a school project as a part of a tools development class at my Uni and we need people to be able to see it. Elsewise, it would currently be a private state.

**Comment by Kaiymu** [comment]
No problem at all !
I looked at your code and wanted to bring some input about that :).

**Comment by crazyjackel** [comment]
> No problem at all ! I looked at your code and wanted to bring some input about that :).

I would recommend forking the repo at this state, if you want to use it, btw.
